name: Update Rutube Stream
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium webdriver-manager requests
          
      - name: Run M3U8 Updater
        run: |
          python get_rutube_m3u8.py || echo "Попытка получения ссылки не удалась"
          
      - name: Upload debug info
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debug-info
          path: debug/
          
      - name: Commit and Push
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rutube.m3u
          git diff-index --quiet HEAD || git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
          git push
