name: Update Rutube Stream
on:
  schedule:
    - cron: '0 */2 * * *'  # Каждые 2 часа
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - run: pip install requests
      
      - name: Get M3U8 link
        run: python get_rutube_m3u8.py
        
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "Update stream link" || echo "No changes"
          git push
