name: Update Rutube M3U8 Link
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Явно даем права на запись
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch M3U8 URL
        run: python get_rutube_m3u8.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add m3u8_link.txt
          
          # Проверяем изменения
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update M3U8 link [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
