name: Update Rutube M3U8 Link
on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:      # Ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов
          token: ${{ secrets.GITHUB_TOKEN }}  # Явное указание токена

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch M3U8 URL
        run: python get_rutube_m3u8.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Обновляем ветку перед пушем
          git pull --rebase
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add m3u8_link.txt
          
          # Проверяем, есть ли изменения для коммита
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update M3U8 link [skip ci]"
            git push origin HEAD:main
          fi
